- src/neon/neonrequest.cpp
configureRequest() of neonrequest.cpp is called a second time if there is a redirect. This results in the extra header fields being added twice to the resulting request.
I'm not entirely sure if this is the correct way to fix it - could `_headers_field` contain anything useful at that point of execution?
Cheers, Georgios
> DMC-729 Fix --header being sent twice on redirect

- src/fileops/httpiovec.cpp
Request offset: 18605275 Size: 3484
Request offset: 30007072 Size: 2243
Request offset: 52081502 Size: 5290
DAVIX(chain): Davix::parseMultipartRequest::copyChunk copy 18605275 bytes with offset 3484
DAVIX(chain): Davix::parseMultipartRequest::copyChunk copy 30007072 bytes with offset 2243
DAVIX(chain): Davix::parseMultipartRequest::copyChunk copy 52081502 bytes with offset 5290
> debug message not correctly formated

- CMakeLists.txt
While CMakeLists.txt was searching for the uuid library and header it
did not add the header to the include path so it could not be used from
non-standard locations.
> Fix uuid.h in non-standard location

- cmake/modules/Finduuid.cmake
On macOS there is no need for libuuid.so, the functions are provided
by the kernel, and the header comes with the OS. The updated file
only looks for a libuuid.so if it is needed.
> Update Finduuid.cmake to work on macOS

- cmake/modules/Finduuid.cmake
Before, `UUID_LIBRARIES` would only get set to `UUID_LIBRARY` if not already set by the user.
This is an alternative fix to #28.
> Always set UUID_LIBRARIES to UUID_LIBRARY if it's defined

- cmake/modules/Finduuid.cmake
* There is some weird CMake behavior where CMake is unable to check for
the existence of directories in some cases
* If UUID_LIBRARY is given and _uuid_head_only is not set the
UUID_LIBRARIES variable was never set, leading to undefined symbols in
libdavix.so
> Fix some problems in Finduuid.cmake

- cmake/modules/FindSphinx.cmake
The test gives warnings with python 3.
```
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Checking for package 'Sphinx'
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.7") 
File "<string>", line 1
import sphinx; print sphinx.__version__
^
SyntaxError: invalid syntax
-- Found Sphinx: /usr/bin/sphinx-build  
```
With the PR:
```
-- Checking for package 'Sphinx'
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.7")
-- Found Sphinx: /usr/bin/sphinx-build
```
> Python 3 compat

- CMakeLists.txt
This is attempt number 2 after #37. 😛
As explained in that pull request, I'm trying to make it easier to build Davix on platforms that don't have the `python2` executable available in a standard location.
Following @gbitzes's recommendation, I simplified the original pull request greatly by just using `${PYTHON_EXECUTABLE}` explicitly in the project's main `CMakeLists.txt` file.
> Python Usage Update, devel branch (2019.01.21.)

- docker/Dockerfile
- docker/README.md
- docker/davix.sh
This adds Docker support to davix and allows the creation of easy-to-use Docker images for all existing branches and/or releases. Files needed for Docker support are confined in a new `docker` sub-directory and documentation is provided in the `README.md` file. These files should be enough for automatically creating images at the Docker [hub](https://hub.docker.com/)
> Adding Docker support

- src/modules/copy/delegation/delegation.cpp
Delegation code always returns error even in case of successfully delegated proxy. This means TPC always fails in case there is not yet proxy delegated in the past to the storage (e.g. after client refresh its voms proxy). This is causing also a lot of WebDAV TPC transfer failures initiated by FTS, because its credentials are refreshed every hour and storage sited can have multiple diskserver where first transfer with refreshed proxy fails.
> Fix error handling for proxy delegation

- src/neon/neonrequest.cpp
Would fix the problem described in [DMC-1209](https://its.cern.ch/jira/browse/DMC-1209).
It's a simple solution that addresses the problem in the top-level `NeonRequest::redirectRequest()`.
Perhaps the problem can be solved more elegantly down the line in the `StandaloneRequest` implementations of both NEON or CURL.
> [DMC-1209]: Transform redirect location relative path into full URI

- deps/libneon/src/ne_openssl.c
With verbose log level davix prints details about server certificate chain, but it doesn't correctly terminate output data with '\0' character before passing data to "%s" formatting.
> Really add '\0' after printed X.509 data

- include/davix/params/davix_request_params_types.hpp
- include/davix/params/davixrequestparams.hpp
- include/davix/utils/davix_swift_utils.hpp
- src/CMakeLists.txt
- src/fileops/davmeta.cpp
- src/fileops/davmeta.hpp
- src/params/davixrequestparams.cpp
- src/tools/davix_tool_ls_main.cpp
- src/tools/davix_tool_params.cpp
- src/utils/davix_swift_utils.cpp
- src/xml/swiftpropparser.cpp
- src/xml/swiftpropparser.hpp
- test/functional/davix-tester.cpp
- test/unit/xml-parser.cpp
Add listing function for Swift. 
One can use command 'davix-ls <url> --osprojectid <id> --ostoken <token>' for listing, optionally, '--swift-listing' can be used to list directories in semi-hierarchical or hierarchical way.
> Swift list collection

- src/CMakeLists.txt
- src/fileops/SwiftIO.cpp
- src/fileops/SwiftIO.hpp
- src/fileops/chain_factory.cpp
- src/tools/davix_tool_put_main.cpp
Add uploading files function for Swift, with multipart upload considered. 
One can use 'davix-put local/file/path swifts://.. --ostoken $token --osprojectid $id' to upload local file to Swift, and use '-r' option to upload a directory of files to Swift. One can use fragment '#forceMultipart' to make use of [multipart upload](https://docs.openstack.org/swift/latest/overview_large_objects.html#module-swift.common.middleware.slo) supported by Swift.
Multipart upload is used for files > 512MB. In this case, a large file is uploaded in a set of segments of maximum size 256MB. The default maximum segment number in one multipart manifest in Swift is 1000, hence, large files that exceed the 1000 limit in segments will be uploaded in an inline manner (where the file is represented by manifests …
> Swift write from provider

- src/fileops/davmeta.hpp
- test/functional/davix-tester.cpp
The handling of checksum for S3 can be used for Swift, thus, no additional function is added for Swift.
But the davix-tester does not have the option to verify the checksum, so I added a function there to get the checksum of a file. I also added a 'fulltest-swift' option for Swift, as is the case with S3/Azure.
> add command checksum to davix-tester

- include/davix/params/davix_request_params_types.hpp
- include/davix/params/davixrequestparams.hpp
- src/fileops/davmeta.cpp
- src/fileops/davmeta.hpp
- src/params/davixrequestparams.cpp
- src/tools/davix_tool_params.cpp
- src/tools/davix_tool_params.hpp
- src/tools/davix_tool_util.cpp
- src/utils/davix_swift_utils.cpp
- test/functional/davix-tester.cpp
1. Added move function for Swift.
2. Added option --swift-account in addition to --os-project-id for accessing Swift. This is because Swift API makes use of URL format /v1/{account}/{container}/{object}. When Keystone auth is configured for Swift, which is usually the case, the {account} part is AUTH_{os_project_id}. In the case that another auth system is configured, users need a Swift account to access Swift. Davix should be able to support this scenario as well.
> Swift move

- src/fileops/iobuffmap.cpp
When the end of the file is reached, `ret` will be 0 and the total number
of bytes read should be returned.
Potential fix for #69.
> Fix return value of `HttpIO::readFull`

- src/curl/CurlSessionFactory.cpp
- src/neon/neonsessionfactory.cpp
This initialization was dropped during curl backend development.
> Initialize session factory members

- src/libs/alibxx/str/format.hpp
This PR fixes errors like:
error: 'move' has not been declared in 'Davix::std'
error: 'size_t' in namespace 'Davix::std' does not name a type
error: 'Davix::std::size_t' has not been declared
error: 'basic_string' in namespace 'Davix::std' does not name a template type
error: class 'Davix::fmt::BasicStringRef<Char>' does not have any field named 'size_'
error: 'char_traits' is not a member of 'Davix::std'
These errors occurred with gcc 12 on Fedora 36 (rawhide).
> Do not #include inside a namespace

- src/curl/StandaloneCurlRequest.cpp
~~~
.../src/curl/StandaloneCurlRequest.cpp:440:13: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
440 |   while(msg = curl_multi_info_read(_session->getHandle()->mhandle, &msgs_left)) {
|         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~
> Add parentheses around assignment used as truth value

- test/drunk-server/DrunkServer.cpp
~~~
.../test/drunk-server/DrunkServer.cpp:116:23: warning: moving a local object in a return statement prevents copy elision [-Wpessimizing-move]
116 |       return std::move(conn);
|              ~~~~~~~~~^~~~~~
.../test/drunk-server/DrunkServer.cpp:116:23: note: remove 'std::move' call
~~~
> Remove std::move from return statement

- src/fileops/davmeta.cpp
~~~
.../src/fileops/davmeta.cpp:168:25: warning: comparison of integer expressions of different signedness: 'int' and 'const size_type' {aka 'const long unsigned int'} [-Wsign-compare]
168 |                 if (pos == std::string::npos) {
|                     ~~~~^~~~~~~~~~~~~~~~~~~~
~~~
> Use sensible string size type

- src/curl/StandaloneCurlRequest.cpp
- src/modules/copy/delegation/GRSTx509MakeProxyCert.cpp
~~~
.../src/curl/StandaloneCurlRequest.cpp:308:10: warning: unused variable 'mhandle' [-Wunused-variable]
308 |   CURLM* mhandle = _session->getHandle()->mhandle;
|          ^~~~~~~
.../src/modules/copy/delegation/GRSTx509MakeProxyCert.cpp:116:8: warning: unused variable 'serial' [-Wunused-variable]
116 |   long serial = 1234, ptrlen;
|        ^~~~~~
~~~
> Remove unused variables

- src/CMakeLists.txt
- src/modules/copy/CMakeLists.txt
See: cmake --help-policy CMP0022
> Fix cmake warning

- CMakeLists.txt
- test/slow-unit/CMakeLists.txt
This includes again the `CTest` module so that tests can be run with `make test` or just `ctest`.
> Re-enable test to be run with ctest (or make test / ninja test)

- .mailmap
This file is used to map author and committer names and email addresses to canonical real names and email addresses. This is useful when using git blame, git shortlog, etc. For more information, see gitmailmap(5).
> Add git mailmap file

- test/unit/content-provider.cpp
Test fails when EBADF != 9:
[----------] 7 tests from ContentProvider
[ RUN      ] ContentProvider.Fd
./test/unit/content-provider.cpp:93: Failure
Expected equality of these values:
provider.pullBytes(buffer, 3)
Which is: -1073741833
-9
[  FAILED  ] ContentProvider.Fd (0 ms)
From /usr/include/i386-gnu/bits/errno.h:
EBADF                          = 0x40000009,  /* Bad file descriptor */
> Do not hardcode error numbers

- patch-curl-clock-gettime.sh
> Use sed in a more POSIX compliant way

- src/file/davposix.cpp
- src/fileops/S3IO.cpp
- src/fileops/S3IO.hpp
- src/fileops/SwiftIO.cpp
- src/fileops/httpiochain.cpp
- src/fileops/httpiochain.hpp
- src/utils/CompatibilityHacks.cpp
- src/utils/davix_logger.cpp
This minimal pull request allows a client to specify that POSIX write requests should use multipart streaming via an envar DAVPOSIX_MPUPLOAD. If the envar is not set the original code path is used and uploads work just as before. This option is meantto be used by S3 proxy servers that cannot tolerate the creation of an intermediate file on POSIX write uploads.
> Implement multipart streaming for DavPosix::write()

- deps/libneon/config.cmake.in
Debian recently enabled 64 bit time_t on most of their 32 bit architectures by default. Since it is not possible to have a 64 bit time_t and a 32 bit off_t, this means that also large file support (64 bit off_t) was enabled by default. This PR addresses some format warnings due to this change.
> Support 64 bit off_t on 32 bit systems (LFS)

- src/fileops/davmeta.cpp
- src/xml/davxmlparser.hpp
- src/xml/s3propparser.cpp
- src/xml/s3propparser.hpp
As describe in issue #122, current s3 dirlisting ignores the istruncated=true and nextmarker in s3 response to listobject. This pull request will fix that issue.
> Fix s3 dirlisting to follow the istruncated/nextmarker
